### ISSUE TITLE
SyncDictionary is not working

### ISSUE THREAD

**Issue by Lanboost** [James-Frowen/Mirage.Godot#1] opened 2023-10-05 17:17 UTC
I think SyncDictionary is not working.

I get
```
         [Error]: Exception :System.NullReferenceException: Object reference not set to an instance of an object.
            at Mirage.Weaver.SyncObjectProcessor.GenerateReadersAndWriters(TypeReference tr) in ...\Mirage.Godot\src\Mirage.Core\Mirage.CodeGen\Weaver\Godot\SyncObjectProcessor.cs:line 83
            at Mirage.Weaver.SyncObjectProcessor.GenerateReadersAndWriters(TypeReference tr) in ...\Mirage.Godot\src\Mirage.Core\Mirage.CodeGen\Weaver\Godot\SyncObjectProcessor.cs:line 83
            at Mirage.Weaver.SyncObjectProcessor.GenerateReadersAndWriters(TypeReference tr) in ...\Mirage.Godot\src\Mirage.Core\Mirage.CodeGen\Weaver\Godot\SyncObjectProcessor.cs:line 83
            at Mirage.Weaver.SyncObjectProcessor.ProcessSyncObjects(TypeDefinition td) in ...\Mirage.Godot\src\Mirage.Core\Mirage.CodeGen\Weaver\Godot\SyncObjectProcessor.cs:line 53
            at Mirage.Weaver.NetworkBehaviourProcessor.Process() in ...\Mirage.Godot\src\Mirage.Core\Mirage.CodeGen\Weaver\Godot\NetworkBehaviourProcessor.cs:line 71
            at Mirage.Weaver.Weaver.WeaveNetworkBehavior(FoundType foundType) in ...\Mirage.Godot\src\Mirage.Core\Mirage.CodeGen\Weaver\Weaver.cs:line 162
            at Mirage.Weaver.Weaver.Process(AssemblyDefinition assembly, CompiledAssembly compiledAssembly) in ...\Mirage.Godot\src\Mirage.Core\Mirage.CodeGen\Weaver\Weaver.cs:line 73
         
```

When creating a 
```
public readonly SyncDictionary<int, int> test = new SyncDictionary<int, int>();
```

**Comment by James-Frowen** [comment] 2023-10-05 18:13
I think this is caused by it not resolving the system types correctly.

Added some extra null checks which should stop the error https://github.com/James-Frowen/Mirage.Godot/commit/ad225f56e3d1d0c1ae031125c5f6208b837791fa

**Closed by James-Frowen** 2023-10-05 18:13 UTC
